version: '3.7'

networks:
  huohuade:
    driver: bridge

services:

  app:
    build:
      args:
        user: muha
        uid: 1000
      context: ./Dockerfiles/
      dockerfile: nginx.dockerfile
    ports:
      - 80:80
    container_name: huohuade_app
    volumes:
      - ./src:/var/www/huohuade:delegated
    depends_on:
      - php
      - mysql
    networks:
      - huohuade

  php:
    build:
      args:
        user: muha
        uid: 1000
      context: ./Dockerfiles/
      dockerfile: php.dockerfile
    container_name: huohuade_php
    ports:
      - 9000:9000
    volumes:
      - ./src:/var/www/huohuade:delegated
      - ./Dockerfiles/php.ini:/usr/local/etc/php/conf.d/local.ini
    networks:
      - huohuade

  mysql:
    image: mysql:8.1.0
    restart: always
    tty: true
    ports:
      - "3306:3306"
    volumes:
      - ./mysql:/var/lib/mysql
    container_name: huohuade_mysql
    environment:
      MYSQL_DATABASE: huohuade
      MYSQL_USER: huohuade
      MYSQL_PASSWORD: huohuade
      MYSQL_ROOT_PASSWORD: huohuade
      SERVICE_TAGS: dev
      SERVICE_NAME: mysql
    networks:
      - huohuade
      
  composer:
    build:
      context: ./Dockerfiles/
      dockerfile: php.dockerfile
      args:
        user: muha
        uid: 1000
    container_name: huohuade_composer
    volumes:
      - ./src:/var/www/huohuade:delegated
    depends_on:
      - php
    entrypoint: [ 'composer', '--ignore-platform-reqs' ]
    networks:
      - huohuade

  npm:
    image: node:21
    container_name: huohuade_npm
    volumes:
      - ./src:/var/www/huohuade
    ports:
      - "3000:3000"
      - "3001:3001"
      - "5173:5173"
    working_dir: /var/www/huohuade
    entrypoint: [ 'npm' ]
    networks:
      - huohuade

  artisan:
    build:
      context: ./Dockerfiles/
      dockerfile: php.dockerfile
      args:
        user: muha
        uid: 1000
    container_name: huohuade_artisan
    volumes:
      - ./src:/var/www/huohuade:delegated
    depends_on:
      - mysql
    entrypoint: [ 'php', '/var/www/huohuade/artisan' ]
    networks:
      - huohuade

