version: '3.7'

networks:
  huohuade:
    driver: bridge

services:

  app:
    build:
      args:
        user: muha
        uid: 1000
      context: ./Dockerfiles/
      dockerfile: nginx.dockerfile
    ports:
      - 8081:80
    container_name: huohuade_app
    volumes:
      - ./src:/var/www/huohuade:delegated
    depends_on:
      - php
      - mysql
      - mongodb
    networks:
      - huohuade

  php:
    build:
      args:
        user: muha
        uid: 1000
      context: ./Dockerfiles/
      dockerfile: php.dockerfile
    container_name: huohuade_php
    ports:
      - 9001:9000
    volumes:
      - ./src:/var/www/huohuade:delegated
      - ./Dockerfiles/php.ini:/usr/local/etc/php/conf.d/local.ini 
    networks:
      - huohuade

  mysql:
    image: mysql:8.1.0
    restart: always
    tty: true
    ports:
      - "3307:3306"
    volumes:
      - ./mysql:/var/lib/mysql
    container_name: huohuade_mysql
    environment:
      MYSQL_DATABASE: huohuade
      MYSQL_USER: huohuade
      MYSQL_PASSWORD: huohuade
      MYSQL_ROOT_PASSWORD: huohuade
      SERVICE_TAGS: dev
      SERVICE_NAME: mysql
    networks:
      - huohuade
      
  mongodb:
    image: mongo:7.0.2
    container_name: huohuade_mongodb
    restart: always
    tty: true
    ports:
      - "27018:27017"
    volumes:
      - ./mongodb:/data/db
    working_dir: /var/www/huohuade
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example 
    networks:
      - huohuade
      
  composer:
    build:
      context: ./Dockerfiles/
      dockerfile: php.dockerfile
      args:
        user: muha
        uid: 1000
    container_name: huohuade_composer
    volumes:
      - ./src:/var/www/huohuade:delegated
    depends_on:
      - php
    entrypoint: [ 'composer', '--ignore-platform-reqs' ]
    networks:
      - huohuade

  npm:
    image: node:20.8.1
    container_name: huohuade_npm
    volumes:
      - ./src:/var/www/huohuade
    ports:
      - "3000:3000"
      - "3001:3001"
      - "5173:5173"
    working_dir: /var/www/huohuade
    entrypoint: [ 'npm' ]
    networks:
      - huohuade

  artisan:
    build:
      context: ./Dockerfiles/
      dockerfile: php.dockerfile
      args:
        user: muha
        uid: 1000
    container_name: huohuade_artisan
    volumes:
      - ./src:/var/www/huohuade:delegated
    depends_on:
      - mysql
      - mongodb
    entrypoint: [ 'php', '/var/www/huohuade/artisan' ]
    networks:
      - huohuade

  schedule:
    build:
      context: ./Dockerfiles/
      dockerfile: php.dockerfile
      args:
          user: muha
          uid: 1000
    command: ['php','artisan', 'schedule:work' ]
    container_name: huohuade_schedule
    restart: always
    volumes:
      - ./src:/var/www/huohuade:delegated
    depends_on:
      - php
    networks:
      - huohuade
